### ISSUE TITLE
#5 45.02 E: Unable to locate package winehq-stable

### ISSUE THREAD

**Issue by Casuallynoted** [antimomentum/haloce#1]
I'm getting the above error after trying to build the docker container. It seems like maybe somehow it's not able to fetch wine from the repository. I'm happy to provide any additional information, so far I don't see any other errors in the docker build . logs.

**Comment by antimomentum** [comment]
I'll have to look into the Wine installation for Ubuntu 18. In the meantime the Dockerfile now uses Debian 9 for the base image, it seems to be more stable anyways even when it's running on a host Ubuntu 18 system. It even boots faster and is smaller in size.

Also thanks for the report!
