### ISSUE TITLE
the servers won't ping and won't connect

### ISSUE THREAD

**Issue by Cr3am** [antimomentum/haloce#2]
when executing the command  docker run -it -p 2302:2302/udp antimomentum/haloce  or when I run the server made by me it works only that when I see the server in the list of servers it appears yes but without ping and it does not allow connecting to it
![image](https://user-images.githubusercontent.com/74673312/108538160-7f437200-72ac-11eb-8fd7-7a85fc5153aa.png)

**Comment by antimomentum** [comment]
I'd be glad to help! 

Are you using my firewall with it? If not, something else is blocking it or misconfigured somehow. If so, did you change any rules?
I recommend troubleshooting with tshark: apt install tshark
Then while trying to connect to your server as a player do:
tshark -i docker0
This will show if the docker0 interface is even seeing the packets, as well as show if the halo server is responding. If it's responding look at the public interface to see if they leave the server:
tshark -i eth0

The fact that it shows up in the list means the Master dns and natneg servers were able to be contacted via DNS (the two IPs you see in the MDNS table of my firewall are the Master dns/natneg), but something else is either misconfigured or flat out blocking you

Also other firewalls may interfere. For example ufw, you can check it with: ufw status

**Comment by Cr3am** [comment]
so I was reading a bit the server if it opens its ports but does not hear them
![image](https://user-images.githubusercontent.com/74673312/108899519-82a96700-75e6-11eb-9ded-45552fdaf32d.png)

**Comment by antimomentum** [comment]
Are you running Docker in Windows? If so I think Windows Firewall (or whatever firewall you're using) is blocking access to Docker itself or you need to configure Docker Desktop to have access to the host. The container is not made to block any outside access.

**Comment by Cr3am** [comment]
no, I am running on Ubuntu 18.04 LTS

**Comment by antimomentum** [comment]
hmm it shouldn't need port 2303. What's the docker run command you're using?

**Comment by Cr3am** [comment]
docker run -it -p 2302:2302/udp antimomentum/haloce

**Comment by Cr3am** [comment]
but I did it in digitalocean servers and in vurt and it doesn't work either which I think you have to check the new docker rules because something is wrong
