### ISSUE TITLE
Ip used in games list incorrect (Question)

### ISSUE THREAD

**Issue by Ewoodss** [antimomentum/haloce#4]
everything works fine i use dirrect connect, but if i try to connect via the gameslist it trys to connect to the wrong ip, this is a internal ip. 

i am using your docker container inside kubernetes with a node port.
is there a way to tell the halo server what the external ip is, because everything else works fine?

or is this a unsopperted use case?

**Comment by antimomentum** [comment]
there is an ip switch for haloceded.exe, just like its -path and -port switches. -IP I think. But I would not expect this to fix the issue.

it sounds like either the master server or the natneg server (or both) are unable to reach the halo server for some reason. When the halo server starts, even if it gives a local ip or wrong ip in the data segment, as long as packets are getting to and from the master and halo server it will still get the public ip that the master/natneg see the halo packets coming from.

In fact the halo server running in just a basic Docker setup sends a local ip of 127.0.0.1 to the master server in the data if I recall correctly, this is why I don't think the -IP haloceded switch will matter.

Sounds more like maybe a port or ip address translation issue this is usually the cause. When starting a halo server, i recommend capturing on each interface (real and virtual) to see where the packet gets dropped, examples: tshark -i eth0 and tshark -i docker0 

I've also found these rules helpful, especially when doing a reverse proxy setup (without Docker). Perhaps if nothing else they'll offer some insight to the needed ports. Ignore the source ip this was a reverse proxy for a wine halo server:

iptables -t nat -A PREROUTING -s 10.0.0.2 -m length --length 59 -m udp -p udp --dport 27900 -j DNAT --to-destination 54.82.252.156:27900

iptables -t nat -A PREROUTING -s 10.0.0.2 -m udp -p udp --dport 27900 -j DNAT --to-destination 34.197.71.170:27900

Make sure the port of the halo server, and that 27900 port for both ips remain correct accross the interfaces. 

I would bet when the halo server starts one of those ips (34.197.71.170 and 54.82.252.156) are getting lost in translation if not the port number. In which case a rule like this for the interface may help: iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE

**Comment by Ewoodss** [comment]
![halo](https://user-images.githubusercontent.com/70382659/177648868-09259671-9b01-4cb8-808f-b2873a1f6c19.png)
i am using the default config, i am running inside of kubernetes. the ip that gets listed in the gameview is the pods ip address.
the game works great if i just type in my ip by hand, i am using the default port. setting the -IP flag didn't change anything.

i understand my use case is not pure docker so np keeping this closed.

**Comment by Ewoodss** [comment]
[HaloDump.zip](https://github.com/antimomentum/haloce/files/9067530/HaloDump.zip)
I made a network dump of the network traffic during startup of the server. in this you can see it sends the wrong ip address to 34.197.71.170. is there a way to intercept this traffic and replace it with the correct ip address. the gamebrowser uses the ip it gets send in this package and not the ip the packet is comming from. i will try to find a solution myself if you have any input that would be grately appreciated

**Comment by Ewoodss** [comment]
direct connect with my public ip does work. also when not on the same network tested using 4g network. only the game browser connection doesn't work when not on same network. i got it work when on the same network by switching to host networking but then the gamelist just advertises the local ip so it work's but only because i am on the same network.

**Comment by Ewoodss** [comment]
setting the -ip flag doesn't work because it can't bind to my public ip address because it's inside a container, so i get an error and no one can connect not even locally.

**Comment by antimomentum** [comment]
> [HaloDump.zip](https://github.com/antimomentum/haloce/files/9067530/HaloDump.zip) I made a network dump of the network traffic during startup of the server. in this you can see it sends the wrong ip address to 34.197.71.170. is there a way to intercept this traffic and replace it with the correct ip address. the gamebrowser uses the ip it gets send in this package and not the ip the packet is comming from. i will try to find a solution myself if you have any input that would be grately appreciated

The first thing I'm noticing from the pcap is that there are no packets received from 54.82.252.156
Both 34.197.71.170 and 54.82.252.156 are required to be allowed in order for the server be joinable from the server list. 

In fact, what your halo server says the ip is does not matter and I'll show you a pcap of this, you'll notice my server in the container also sends 34.197.71.170 a local docker ip as well which is 172.17.0.2 in this case.
[halotest.zip](https://github.com/antimomentum/haloce/files/9076252/halotest.zip)
(the halo server should also respond to that ip, I think I stopped the capture buffer short by accident)

I think a firewall is blocking the 54 ip thus preventing nat negotiation for your server. If you're running it from a home or cell ISP their firewalls are typically based on "established" connections meaning you have to send a packet to the ip before the ip is allowed to be received. Cloud servers that I run my server on do not typically have this automatic "established" firewall setting in place so this isn't an issue I run into despite halo saying it's using that local docker ip.


Also halo servers do get DDoS'd from time to time especially when full so I would NOT try to run one through a cell connection or you could end up facing large charges. Even with "unlimited" data you could get throttled. Running from home will expose your public ip as well.

**Comment by drewdrew21b** [comment]
I am seeing this with 3 different docker hosts, all of them end up reporting my docker IP when I try to connect from the internet. Did something change with Docker in the last several years? Any other suggestions to make this work OOTB?

**Comment by antimomentum** [comment]
**docker run -it -p 2302:2302/udp antimomentum/halo** does run OOTB and is join-able and visible in the list (starts at 0/1 players, arrange list by players to see it quick)

I'll explain the halo server list process. The halo server starts it:

1. the 1st packet in the data/payload segment from your halo server does contain whatever "machine" ip it thinks it's running from. But if that's not a public ip that is ignored by the Master Server and the MS just uses the public source ip it saw in the ip header, not the ip the halo server data reported to it :) The MS might just only go with the ip header source ip!

2. The _master server_ (ip starts wth 34) then tells the halo nat negotiation server (ip starts with 54) what source public ip and source port to reply back to _your_ halo server with. THIS is where most people run into issues. A firewall is probably blocking this reply and even CGNAT can break this process. 

But this is also because main home/residential ISPs normally just block ips you didn't request in the first place (DNS for a website name is used to get your browser to send a request to an ip first for instance). You shouldn't run into this issue on most public cloud hosts

If 1 was successful but 2 was not your server will show in the list but it won't be join-able and have no ping! (Again this is where most people run into issues starting any halo ce server). If 2 worked:

3. The halo server and master exchange some more packets and the server becomes both visible in the list and join-able
