### ISSUE TITLE
Network Connection Lost

### ISSUE THREAD

**Issue by michaellunzer** [antimomentum/haloce#6]
Hey @antimomentum great job with this project! I'm trying to get it running on my home server.

I've used the [docker compose file](https://github.com/antimomentum/haloce/blob/master/Dockerfiles/docker-compose.yml) to deploy it on Portainer. 

On my Windows 10 desktop with Halo installed, I'm going to Multiplayer -> Join Game -> Direct IP -> and then putting in the IP address of the server where the docker container is deployed. (192.168.1.111). I've tried it with the port _:2302_ at the end and get the same result = It says it's connected and loading the map Blood Gultch then after a bit says "Network Connection Lost"

I'm checking the logs on the container and it seems to be running. However, it is strange that it only says _0/1 players_. The output is:

```
Dedicated server is running on map bloodgulch (0 / 1 players)
Use the 'sv_end_game' command to stop the game.
```

When that didn't work I stopped the containers created above and ran this from the command line: 
`docker run -e INTERNAL_PORT=2302 -it -p 2302:2302/udp antimomentum/halo`

The logs show:

`halo(Dedicated server is running on map bloodgulch (0 / 16 players)`

Again I'm unable to directly connect to the IP of the server. The default port 2302 matches the settings and doesn't make a difference if it's added after the IP or not. 

I feel like I'm close but maybe you can point me in the right directIon. Thanks again!

**Comment by michaellunzer** [comment]
@haloss1 any input from you would also be appreciated!

**Comment by antimomentum** [comment]
Hi michaellunzer, thanks!

Unfortunately I'm not familiar with running docker in Windows or Portainer. Docker by default creates a bridged network however:

https://docs.docker.com/network/

using a network of something like 172.17.0.1/16. I'm not sure how Portainer effects this.

I would guess that you might need to direct ip to an ip in that network rather than 192.168.1.111

I would recommend installing something like Wireshark or Netmon

https://www.wireshark.org/download.html
https://docs.microsoft.com/en-us/windows-hardware/drivers/portable/using-the-netmon-tool

and running a capture while you try to connect if you still can't connect to the container in the bridged network. If nothing else it should offer you more insight into the issue.


As for it showing 0/1 players rather than 0/16 that is quite odd and I went ahead and checked over inits for that halo container, it's set to 16 maxplayers. There are no scripts that change player number either. Unless you did "sv_maxplayers 1" or altered init.txt to "sv_maxplayers 1" I really don't know what that's about. Maybe a Lua script you are using?

**Comment by haloss1** [comment]
Hi @michaellunzer i'll have a look at it later this day,
What OS do you have on the docker host?

Do you have any firewall on the host or external in your network that might be interfering with the conection between your windows 10 game client and the server?

Could you use https://www.npmjs.com/package/gamedig (Needs Node.js and NPM to use/install) to retrieve the server info and paste it in here?

**Comment by haloss1** [comment]
Oh wait, i see your using another container image, what's the difference between that `antimomentum/composetest` image and the `antimomentum/halo` we have in the [README](https://github.com/antimomentum/haloce#readme) @antimomentum?

**Comment by haloss1** [comment]
There's also a [antimomentum/haloce](https://hub.docker.com/r/antimomentum/haloce), which one is the latest that we did basing from `alpine` @antimomentum?

**Comment by michaellunzer** [comment]
> What OS do you have on the docker host?

I'm running a Proxmox Server with OpenMediaVault5 on a VM. OMV is a Debian based linux distribution and Portainer is just a GUI on a website to run docker containers and add docker-compose.yaml configurations. All the docker activities can also run natively via command line. 

As far as the firewall, typically I don't have to open a port to access a port that is published by a docker container. But, I did just to rule that out:

![image](https://user-images.githubusercontent.com/10967175/161150287-e3c53f5d-9698-49a7-82b8-0eaecec3bf25.png)

I'm trying a this as the docker-compose file -- hoping that this was the right image from the one-liner docker run example:

```
version: "2"
services:
  halo:
    image: antimomentum/halo
    tty: true
    stdin_open: true
    ports:
      - "2302:2302/udp"
    environment:
     - INTERNAL_PORT=2302
```

I'll keep troubleshooting and see if I can get it to work! Let me know if you'd like me to try anything

**Comment by michaellunzer** [comment]
for more info I also ran gamedig from the command line:

`gamedig --type halo 192.168.1.111:2302`

and heres the output:

`{"name":"\u0001","map":"bloodgulch","password":false,"raw":{"hostname":"\u0001","gamever":"01.00.10.0621","hostport":"2302","maxplayers":"16","password":"0","mapname":"bloodgulch","dedicated":"1","gamemode":"openplaying","game_classic":"0","numplayers":"0","gametype":"CTF","teamplay":"1","gamevariant":"Endless CTF","fraglimit":"1000000000","player_flags":"1639972868,1089","game_flags":"65","teams":[{"name":"Red","score_t":"0"},{"name":"Blue","score_t":"0"}]},"maxplayers":16,"players":[],"bots":[],"connect":"192.168.1.111:2302","ping":3}`

When I try connecting to 192.168.1.111:2302 it says "Connected to Server. Loading Blood Gultch" and then eventually times out and I get an error popup saying "Network Connection Lost". 

Any chance the error is on my Windows PC (client) side? I was going to install it to my mac to test but they are all on Big Sur so there isn't support for 32bit apps, which it sounds like Halo CE is in that category.

**Comment by haloss1** [comment]
Hi, thank you @michaellunzer, i tried with this compose file:
```
services:
  halo:
    image: antimomentum/halo
    tty: true
    stdin_open: true
    ports:
      - "2302:2302/udp"
```
My laptop (Arch linux) was my docker host and my desktop (Arch linux) was my client

![Screenshot_20220331_234605](https://user-images.githubusercontent.com/15917301/161210444-9015896f-29e8-42f0-981d-c1c6dde0e8a7.png)

![Screenshot_20220331_234948](https://user-images.githubusercontent.com/15917301/161210616-06594b5c-dc97-4519-ab73-1348069dd633.png)
 
 ```
$ gamedig --type halo 192.168.1.65
{
  "name": "\u0001",
  "map": "bloodgulch",
  "password": false,
  "raw": {
    "hostname": "\u0001",
    "gamever": "01.00.10.0621",
    "hostport": "2302",
    "maxplayers": "16",
    "password": "0",
    "mapname": "bloodgulch",
    "dedicated": "1",
    "gamemode": "openplaying",
    "game_classic": "0",
    "numplayers": "0",
    "gametype": "CTF",
    "teamplay": "1",
    "gamevariant": "Endless CTF",
    "fraglimit": "1000000000",
    "player_flags": "1639972868,1089",
    "game_flags": "65",
    "teams": [
      { "name": "Red", "score_t": "0" },
      { "name": "Blue", "score_t": "0" }
    ]
  },
  "maxplayers": 16,
  "players": [],
  "bots": [],
  "connect": "192.168.1.65:2302",
  "ping": 15
}

 ```

**Comment by haloss1** [comment]
Do you have any packet loss between your windows 10 host and your server @michaellunzer?
Maybe try disabling windows 10 firewall temporarily or testing with another PC as the client
Maybe also try running on a host with a linux distro with plain docker instead of OMV to see if it's the server instead of the client

**Comment by antimomentum** [comment]
> There's also a [antimomentum/haloce](https://hub.docker.com/r/antimomentum/haloce), which one is the latest that we did basing from `alpine` @antimomentum?

The one we built is antimomentum/halo, it was built using the main "Dockerfile" in the Dockerfiles folder:
https://github.com/antimomentum/haloce/blob/master/Dockerfiles/Dockerfile

Like antimomentum/halo, the antimomentum/composetest is built from Alpine (I forgot exactly which alpine) and it and has the port variable as well.
CMD wineconsole --backend=curses haloceded -path . -port ${INTERNAL_PORT}


antimomentum/haloce is the old Debian9 version that doesn't have a variable for the port number, built using this:
https://github.com/antimomentum/haloce/blob/master/Dockerfiles/Dockerfile-Debian9

There's also antimomentum/winconsole-lite (wine installed to alpine)
and antimomentum/wineconsole (wine in Debian 9) 
which do not have any halo files put in them, just the base official OS image + apt wine installs that run files. They run halo files supplied by the host, such as a host directory halopull in this example:

i=2304
docker run -it -v ~/halopull:/game -w /game -p $i:$i/udp --add-host=s1.master.hosthpc.com:34.197.71.170 --add-host=hosthpc.com:34.197.71.170 antimomentum/wineconsole-lite wineconsole haloceded.exe -path . -port $i


Or like the vpn linuxclient guided installs, built locally like this:

FROM i386/alpine:3.13
RUN apk add --no-cache wine freetype ncurses


docker build -t halo/wineconsole .


And then ran the same way just different container tag:

i=2304
docker run -it -v ~/halopull:/game -w /game -p $i:$i/udp --add-host=s1.master.hosthpc.com:34.197.71.170 --add-host=hosthpc.com:34.197.71.170 halo/wineconsole wineconsole haloceded.exe -path . -port $i

**Comment by haloss1** [comment]
Hi @michaellunzer, was your issue resolved?, did you find what was the root of the issue?

**Comment by michaellunzer** [comment]
Thanks for checking in - I haven't had time to troubleshoot it. But I was looking into it now and pulled out an old Windows 10 laptop that had halo installed. I disabled the windows firewall for testing purposes and opened up Halo. I looked in the LAN Lobby section and changed the filter to show empty Servers and the server is showing up! However, the result is the same as when I type in the IP address directly.

Although, I did notice that your screenshot says "Powered by Team Rocket" and mine says "Powered by Gamespy". Maybe we can chat on discord about this and maybe it's the reason why I can't connect? I'm not sure, but my next step is to create an Arch linux desktop VM and install halo to that and see how it behaves. Thoughts?

**Comment by haloss1** [comment]
@michaellunzer  hahaha, the "Powered by Team Rocket" is just the UI.map from the Refined Project, as for discord, yeah my tag is Haloss1#6389
As for the server, i can try to test it if you have a public endpoint where i can connect to the halo server or if you have a zerotier network i can join, i could test using that.

**Comment by michaellunzer** [comment]
Hey @haloss1 I sent you a friend request on Discord. Do you have some time to troubleshoot this with me? 

to simplify the docker compose setup on my server, I ran `docker run -e INTERNAL_PORT=2302 -it -p 2302:2302/udp antimomentum/halo` from my mac and got this error: 


```
wine: created the configuration directory '/root/.wine'
0012:err:ole:marshal_object couldn't get IPSFactory buffer for interface {00000131-0000-0000-c000-000000000046}
0012:err:ole:marshal_object couldn't get IPSFactory buffer for interface {6d5140c1-7436-11ce-8034-00aa006009fa}
0012:err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hres=0x80004002
0012:err:ole:CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, 80004002
0012:err:ole:get_local_server_stream Failed: 80004002
0014:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0014:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
0014:err:ole:apartment_createwindowifneeded CreateWindow failed with error 183
0014:err:ole:apartment_createwindowifneeded CreateWindow failed with error 0
0014:err:ole:marshal_object couldn't get IPSFactory buffer for interface {00000131-0000-0000-c000-000000000046}
0014:err:ole:apartment_createwindowifneeded CreateWindow failed with error 14007
0014:err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hres=0x800736b7
0014:err:ole:CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, 800736b7
0014:err:ole:get_local_server_stream Failed: 800736b7
000b:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
000b:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
0010:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0010:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
0010:err:winediag:gnutls_initialize failed to load libgnutls, no support for encryption
0016:err:winediag:gnutls_initialize failed to load libgnutls, no support for encryption
0016:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0016:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
0018:err:winediag:gnutls_initialize failed to load libgnutls, no support for encryption
0018:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0018:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
Could not load wine-gecko. HTML rendering will be disabled.
wine: configuration in '/root/.wine' has been updated.
ddddddddddddddddddddddddddddddddddddddddddddddddaloceded -path . -port 2302ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd0024:fixme:ntdll:EtwEventRegister ({5eec90ab-c022-44b2-a5dd-fd716a222a15}, 0x10001123, 0x1001e020, 0x1001e038) stub.
0024:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 0x1001bc10, 43) stub
Using profile path ..
dalo Console (1)0029:fixme:winhttp:get_system_proxy_autoconfig_url no support on this platform
0029:fixme:winhttp:WinHttpDetectAutoProxyConfigUrl discovery via DHCP not supported
dReading ban list file (.\banned.txt).


sv_name:


sv_password:


true

    
sv_motd: motd.txt


sv_maxplayers: 16


8
 sv_motd: motd.txt


sv_friendly_fire: 1 = off


60

  
sv_tk_grace: 0s


>> bloodgulchEndless CTF


sv_timelimit: 0 = infinite


sv_log_enabled: 0


Loading SAPP...


Starting threads...


Searching for Halo functions...


Patching Halo's code for codecaves...


Loading commands...


Loading Lua scripts...


Loading settings...

Loading settings...

-- Loading SAPP settings --


Auto Update: disabled


Network Thread: disabledd
Scores to ban aimbotter: 8300


Ban Type: IP Ban, Length: 1440 minutes


Mapcycle will be never restarted if the server is idle.


-- Loading SAPP settings finished --


SAPP Version 10.2.1 CE by seh   , originally by Termy || halo.isimaginary.com


Successfully loaded sapp.dll!
002c:fixme:ver:GetCurrentPackageId (0x155fe9c 0): stub
002d:fixme:ver:GetCurrentPackageId (0x166fe9c 0): stub
002f:fixme:ver:GetCurrentPackageId (0x188fe9c 0): stub
0030:fixme:ver:GetCurrentPackageId (0x199fe9c 0): stub
002e:fixme:ver:GetCurrentPackageId (0x177fe9c 0): stub

Anti Halofp: enabled
sv_name:


sv_maxplayers: 16


sv_public_value: 1


halo(

Dedicated server is running on map bloodgulch (0 / 16 players)

halo(
Use the 'sv_end_game' command to stop the game.


halo(

Use the 'sv_end_game' command to stop the game.
Dedicated server is running on map bloodgulch (0 / 16 players)
dUse the 'sv_end_game' command to stop the game.
dhalo(

Dedicated server is running on map bloodgulch (0 / 16 players)
dUse the 'sv_end_game' command to stop the game.
halo(

Dedicated serv
er is running on map bloodgulch (0 / 16 players)
dUse the 'sv_end_game' command to stop the game.
d
halo(
Dedicated server is running on map bloodgulch (0 / 16 players)
dUse the 'sv_end_game' command to stop the game.
dhalo(

Use the 'sv_end_game' command to stop the game.
Dedicated server is running on map bloodgulch (0 / 16 players)
dUse the 'sv_end_game' command to stop the game.
dhalo(

Dedicated server is running on map bloodgulch (0 / 16 players)
dUse the 'sv_end_game' command to stop the game.
d
halo(
Dedicated server is running on map bloodgulch (0 / 16 players)


Use the 'sv_end_game' command to stop the game.
dhalo( ddReading ban list file (.\banned.txt).
dsv_name:
dsv_password:
dtrue
dsv_motd: motd.txt
dsv_maxplayers: 16
d8dsv_motd: motd.txt
dsv_friendly_fire: 1 = off
d60
dsv_tk_grace: 0s
d>> bloodgulchXEndless CTF
dsv_timelimit: 0 = infinite
dsv_log_enabled: 0
dLoading SAPP...
dStarting threads...
dSearching for Halo functions...
dPatching Halo's code for codecaves...
dLoading commands...
dLoading Lua scripts...
dLoading settings...
d-- Loading SAPP settings --
dAuto Update: disabled
dNetwork Thread: disabled
dScores to ban aimbotter: 8300
dBan Type: IP Ban, Length: 1440 minutes
dMapcycle will be never restarted if the server is idle.
d-- Loading SAPP settings finished --
dSAPP Version 10.2.1 CE by seh   , originally by Termy || halo.isimaginary.com
dSuccessfully loaded sapp.dll!
dAnti Halofp: enabled
dsv_name:
dsv_maxplayers: 16
dsv_public_value: 1
dDedicated server is running on map bloodgulch (0 / 16 players)
dUse the 'sv_end_game' command to stop the game.
dDedicated server is running on map bloodgulch (0 / 16 players)
dUse the 'sv_end_game' command to stop the game.
dDedicated server is running on map bloodgulch (0 / 16 players)
dUse the 'sv_end_game' command to stop the game.
dDedicated server is running on map bloodgulch (0 / 16 players)
dUse the 'sv_end_game' command to stop the game.
dDedicated server is running on map bloodgulch (0 / 16 players)
dUse the 'sv_end_game' command to stop the game.
dDedicated server is running on map bloodgulch (0 / 16 players)
dUse the 'sv_end_game' command to stop the game.
dDedicated server is running on map bloodgulch (0 / 16 players)
dUse the 'sv_end_game' command to stop the game.
dDedicated server is running on map bloodgulch (0 / 16 players)
dUse the 'sv_end_game' command to stop the game.
dhalo( sv_mapcycle_beginadd bloodgulch "Endless CTF"

halo(

halo( antihalofp 1
Dedicated server is running on map bloodgulch (0 / 16 players)


halo( antihalofp 1
Use the 'sv_end_game' command to stop the game.


halo( antihalofp 1
 
Dedicated server is running on map bloodgulch (0 / 16 players)
Use the 'sv_end_game' command to stop the game.
dhalo( antihalofp   

halo( antiha  

halo( anti 

halo( ant 

halo( an 

halo( a 

halo(  e

halo( exi

halo( exit
Unknown command: exit


halo( exit


halo(

halo( exit

halo( antihalofp 1

halo( load

halo(

halo( sv_log_enabled "0"

halo(sv_log_enabled "0"loadexitantihalofp 1load

halo(sv_log_enabled "0"sv_mapcycle_begintimelimit "0" 
Dedicated server is running on map bloodgulch (0 / 16 players)
dUse the 'sv_end_game' command to stop the game.
dhalo( sv_timelimit "0"
mapcycle_begin

halo(

halo( sv_log_enabled "0"

halo(loadantihalofp 1exit
Dedicated server is running on map bloodgulch (0 / 16 players)


0mhalo( exit
Use the 'sv_end_game' command to stop the game.


halo( exit

Dedicated server is running on map bloodgulch (0 / 16 players)
dUse the 'sv_end_game' command to stop the game.
dhalo( exit

Dedicated server is running on map bloodgulch (0 / 16 players)
dUse the 'sv_end_game' command to stop the game.


```

Any thoughts? I can close the issue if you'd like

**Comment by antimomentum** [comment]
> wine: created the configuration directory '/root/.wine'
> 0012:err:ole:marshal_object couldn't get IPSFactory buffer for interface {00000131-0000-0000-c000-000000000046}
> 0012:err:ole:marshal_object couldn't get IPSFactory buffer for interface {6d5140c1-7436-11ce-8034-00aa006009fa}
> 0012:err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hres=0x80004002
> 0012:err:ole:CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, 80004002
> 0012:err:ole:get_local_server_stream Failed: 80004002
> 0014:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
> 0014:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
> 0014:err:ole:apartment_createwindowifneeded CreateWindow failed with error 183
> 0014:err:ole:apartment_createwindowifneeded CreateWindow failed with error 0
> 0014:err:ole:marshal_object couldn't get IPSFactory buffer for interface {00000131-0000-0000-c000-000000000046}
> 0014:err:ole:apartment_createwindowifneeded CreateWindow failed with error 14007
> 0014:err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hres=0x800736b7
> 0014:err:ole:CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, 800736b7
> 0014:err:ole:get_local_server_stream Failed: 800736b7
> 000b:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
> 000b:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
> 0010:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
> 0010:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
> 0010:err:winediag:gnutls_initialize failed to load libgnutls, no support for encryption
> 0016:err:winediag:gnutls_initialize failed to load libgnutls, no support for encryption
> 0016:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
> 0016:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
> 0018:err:winediag:gnutls_initialize failed to load libgnutls, no support for encryption
> 0018:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
> 0018:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
> Could not load wine-gecko. HTML rendering will be disabled.

All of this part of the errors is normal. What's happening is wine is expecting graphics and since this has none it spits out those errors. The halo server exe needs no graphics so that's not actually an issue.

Also, the halo console itself expects "quit" rather than "exit" to close the halo server (which will also cause the antimomentum/halo container to exit).

I'm not sure if that's the error you're asking about though, if not just let me know
